import { Outfit } from "next/font/google";
import "./globals.css";
import App from "./App";
import { ThemeProvider } from "next-themes";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light" // Или установите начальную тему
          enableSystem={true}
          disableTransitionOnChange={true}
        >
          <App>{children}</App>
        </ThemeProvider>
      </body>
    </html>
  );
}
